version: '3'

dotenv: ['.env']

vars:
  INIT_FILE: .vault_init.json
  CONTAINER_RUNTIME: '{{.CONTAINER_RUNTIME | default "docker"}}'
  PROJECT_NAME:
    sh: basename $(pwd)

tasks:
  prereqs:
    desc: Check if all prerequisites are installed
    cmds:
      - which {{.CONTAINER_RUNTIME}}
      - which terraform
      - which jq
      - which curl
      - which uv
      - echo "All prerequisites are installed."
    silent: true

  setup:
    desc: Create virtual environment, install dependencies, and create .env
    cmds:

      - test -f .env || cp .env.example .env
      - uv venv --allow-existing
      - uv pip install -r requirements.txt
    silent: true

  up:
    desc: Start Vault and LDAP containers and wait for readiness
    cmds:
      - "{{.CONTAINER_RUNTIME}} compose up -d --wait"
    silent: true

  down:
    desc: Stop containers and remove volumes
    cmds:
      - "{{.CONTAINER_RUNTIME}} compose rm -vfs"
      - sleep 5

  init:
    desc: Initialize both LDAP and Vault
    cmds:
      - test -f .env || cp .env.example .env
      - task: ldap:init
      - task: vault:init
      - task: vault:unseal
    silent: true

  ldap:init:
    desc: Initialize LDAP with sample data
    cmds:
      - "{{.CONTAINER_RUNTIME}} compose exec ldap ldapadd -x -D \"cn=admin,dc=example,dc=org\" -w adminpassword -f /ldap-example.ldif -c || true"

  ldap:status:
    desc: Check LDAP status and list users
    cmds:
      - "{{.CONTAINER_RUNTIME}} compose exec ldap ldapsearch -x -D \"cn=admin,dc=example,dc=org\" -w adminpassword -b \"ou=People,dc=example,dc=org\" \"(objectClass=inetOrgPerson)\" dn"

  postgres:status:
    desc: Check PostgreSQL status and list databases
    cmds:
      - "{{.CONTAINER_RUNTIME}} compose exec postgres psql -U vaultadmin -d vaultdb -c '\\l'"
      - "{{.CONTAINER_RUNTIME}} compose exec postgres psql -U vaultadmin -d vaultdb -c '\\du'"

  postgres:test-readonly:
    desc: Test Vault dynamic readonly credentials for PostgreSQL
    cmds:
      - |
        source .env
        echo "Generating readonly credentials from Vault..."
        CREDS=$(vault read -format=json database/creds/readonly)
        USERNAME=$(echo $CREDS | jq -r '.data.username')
        PASSWORD=$(echo $CREDS | jq -r '.data.password')
        LEASE_ID=$(echo $CREDS | jq -r '.lease_id')
        echo "Username: $USERNAME"
        echo "Lease ID: $LEASE_ID"
        echo ""
        echo "Testing database connection with readonly credentials..."
        {{.CONTAINER_RUNTIME}} compose exec postgres psql -U $USERNAME -d vaultdb -c 'SELECT COUNT(*) FROM test_data;' || echo "Failed to connect"
        echo ""
        echo "Testing write permissions (should fail)..."
        {{.CONTAINER_RUNTIME}} compose exec postgres psql -U $USERNAME -d vaultdb -c 'CREATE TABLE test_table (id INT);' && echo "ERROR: Should not have write access!" || echo "Correctly denied write access"
        echo ""
        echo "Revoking lease..."
        vault lease revoke $LEASE_ID
        echo "Lease revoked successfully"

  postgres:test-readwrite:
    desc: Test Vault dynamic readwrite credentials for PostgreSQL
    cmds:
      - |
        source .env
        echo "Generating readwrite credentials from Vault..."
        CREDS=$(vault read -format=json database/creds/readwrite)
        USERNAME=$(echo $CREDS | jq -r '.data.username')
        PASSWORD=$(echo $CREDS | jq -r '.data.password')
        LEASE_ID=$(echo $CREDS | jq -r '.lease_id')
        echo "Username: $USERNAME"
        echo "Lease ID: $LEASE_ID"
        echo ""
        echo "Testing database connection with readwrite credentials..."
        {{.CONTAINER_RUNTIME}} compose exec postgres psql -U $USERNAME -d vaultdb -c 'SELECT COUNT(*) FROM test_data;' || echo "Failed to connect"
        echo ""
        echo "Testing write permissions..."
        {{.CONTAINER_RUNTIME}} compose exec postgres psql -U $USERNAME -d vaultdb -c 'CREATE TABLE temp_test (id INT); INSERT INTO temp_test VALUES (1); DROP TABLE temp_test;' && echo "Write access confirmed" || echo "ERROR: Should have write access!"
        echo ""
        echo "Revoking lease..."
        vault lease revoke $LEASE_ID
        echo "Lease revoked successfully"

  postgres:test:
    desc: Test both readonly and readwrite dynamic credentials
    cmds:
      - task: postgres:test-readonly
      - echo ""
      - echo "================================"
      - echo ""
      - task: postgres:test-readwrite

  vault:init:
    desc: Initialize Vault and update .env
    interactive: true
    cmds:
      - |
        . .env
        if [ -f {{.INIT_FILE}} ]; then
          printf "Vault init file already exists. Overwrite? (y/N): "
          read yn
          if [ "$yn" != "y" ] && [ "$yn" != "Y" ]; then
            echo "Initialization skipped."
            exit 0
          fi
        fi
        {{.CONTAINER_RUNTIME}} compose exec -e VAULT_ADDR=$VAULT_ADDR vault vault operator init -format=json > {{.INIT_FILE}}
        if [ -s {{.INIT_FILE}} ]; then
          ROOT_TOKEN=$(jq -r '.root_token' {{.INIT_FILE}})
          sed -i.bak "s/export VAULT_TOKEN=.*/export VAULT_TOKEN=$ROOT_TOKEN/" .env && rm .env.bak
          echo "Vault initialized. Root token updated in .env"
        else
          echo "Failed to initialize Vault or empty output."
          exit 1
        fi
    silent: true

  vault:unseal:
    desc: Unseal Vault
    cmds:
      - |
        . .env
        if [ -f {{.INIT_FILE}} ]; then
          KEYS=$(jq -r '.unseal_keys_b64[]' {{.INIT_FILE}})
          for key in $KEYS; do
            {{.CONTAINER_RUNTIME}} compose exec -e VAULT_ADDR=$VAULT_ADDR vault vault operator unseal $key
          done
        else
          echo "Init file missing. Cannot unseal."
          exit 1
        fi
    silent: true

  vault:status:
    desc: Check Vault status
    cmds:
      - |
        source .env
        vault status

  terraform:apply:
    aliases: [apply]
    desc: Initialize and apply Terraform configuration
    dir: terraform
    cmds:
      - terraform init -upgrade
      - source ./../.env && terraform apply -auto-approve -parallelism=1
      - sleep 20

  terraform:destroy:
    desc: Destroy Terraform resources
    dir: terraform
    cmds:
      - source .env && terraform destroy -auto-approve -lock=false

  test:
    desc: Run pytest suite
    cmds:
      - mkdir -p outputs
      - source .env && ./.venv/bin/python3 -m pytest --cov=tests --cov-report=term-missing --cov-report=xml:outputs/coverage.xml --cov-report=html:outputs/coverage_html --junitxml=outputs/report.xml --html=outputs/report.html --self-contained-html

  lint:
    desc: Run Python linting (flake8, black) and Terraform formatting
    cmds:
      - ./.venv/bin/python3 -m flake8 tests
      - ./.venv/bin/python3 -m black --check tests
      - terraform fmt -check -recursive

  clean:
    desc: Cleanup all temporary files, virtual environments, and Docker resources
    cmds:
      - task: down
      - rm -rf {{.INIT_FILE}} terraform/.terraform terraform/terraform.tfstate terraform/terraform.tfstate.backup .pytest_cache outputs
      - |
        VOLUMES=$({{.CONTAINER_RUNTIME}} volume ls -q -f name={{.PROJECT_NAME}})
        if [ ! -z "$VOLUMES" ]; then
          {{.CONTAINER_RUNTIME}} volume rm $VOLUMES 2>/dev/null || true
          sleep 10
        else
          echo "No volumes to remove."
        fi

        {{.CONTAINER_RUNTIME}} compose volumes
    silent: true

  upgrade:
    desc: Upgrade Vault version and run tests
    cmds:
      - |
        source .env
        VAULT_VERSION=$VAULT_VERSION_UPGRADE {{.CONTAINER_RUNTIME}} compose up -d --force-recreate --wait
        VAULT_VERSION=$VAULT_VERSION_UPGRADE task up
      - task: vault:unseal
      - task: vault:status
      - sleep 10
      - task: test
    silent: true

  all:
    desc: Run everything
    cmds:
      - task: prereqs
      - task: lint
      - task: up
      - task: init
      - task: apply
      - task: test
